### ISSUE TITLE
It's a bit difficult to see what has changed

### ISSUE THREAD

**Issue by rikhuijzer** [StatisticalRethinkingJulia/StatisticalRethinking.jl#106]
Hi Rob! First of all, I very much appreciate everything in StatisticalRethinkingJulia. A lot of work is done here. It's great to have some more examples available apart from the tutorials on Turing.ml. 

One thing I am struggling a bit with is to track the history of these repositories. For example, when I look at [Franklin.jl's history](https://github.com/tlienart/Franklin.jl/commits/master), I can quickly have a good idea of what has changed in the last week. With this repository it's a bit more difficult since a commit like "Rel 3.17" could either change the behavior of the package (https://github.com/StatisticalRethinkingJulia/StatisticalRethinking.jl/commit/fd83285c2416ba385723e6f073b541c6442debc8), or could be the version bump (https://github.com/StatisticalRethinkingJulia/StatisticalRethinking.jl/commit/2474f2876ca6f4bc29a48d352c121c7823a32560). For comparison, at Franklin, I don't have to look into a commit called "patch release" because Thibaut always [bumps the version there and triggers JuliaRegistrator. ](https://github.com/tlienart/Franklin.jl/commit/80c46c936ad38b10622ac589938af94c7eb6dfab) 

Of course, maybe you have a good reason for your approach with the commit naming! Then, feel free to close this issue immediately :smile:

**Comment by goedman** [comment]
Hi Rik,  Yes, I've clearly dropped the ball w.r.t. documentation and revision history. I will attempt to follow a more formal workflow in the future for StatisticalRethinking. Thanks for reminding me!

**Comment by rikhuijzer** [comment]
I don’t think you have dropped the ball. Apologies if my issue felt like I was implying that
