### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by EvoArt** [StatisticalRethinkingJulia/StatisticalRethinking.jl#153]
Hi there

Thanks for your work here. How should I cite this package?

**Comment by goedman** [comment]
Hi Arthur, 

Maybe something along the first sentence in the README? I consider Max Lapan and myself (Rob J Goedman) the primary authors of the Julia code. Would that work for you?

Rob

**Comment by EvoArt** [comment]
Yes. That's great, thanks.
