### ISSUE TITLE
Exercise Solutions

### ISSUE THREAD

**Issue by alecloudenback** [StatisticalRethinkingJulia/StatisticalRethinking.jl#7]
Would you be open to pull requests with answers to the solutions at the end of each chapter? 

Either add to `/chapters/[XX]/exercises/` or create a new repo?

Thinking it could be structured as, e.g.  `/chapters/02/exercises/2E` with the four easy responses in there, etc.

It seems like the promised (end of chapter 1) solutions aren't actually to be found online, and it would also be great to have a Julia version of community-driven answers.

**Comment by goedman** [comment]
In your specific example, not really. I’m open to all PRs that make it easier to complete the exercises in Julia, improve presenting the results, etc. But I would like to honor the fact that StatisticalRethinking is a course.

There might be other exercises, maybe in the medium or hard groups, where showing how to do it in Julia, or a different way, is valuable and such PRs we should discuss. This is of course just my opinion and StatisticalRethinkingJulia is a Github organization after all.
